md MessageProto

dotnet Proto2CS.dll

xcopy /s /e /Y /f .\MessageProto\InnerMessage.cs ..\Core\Core\MessageProto\InnerMessage.cs
xcopy /s /e /Y /f .\MessageProto\InnerOpcode.cs ..\Core\Core\MessageProto\InnerOpcode.cs
//xcopy /s /e /Y /f .\MessageProto\OuterMessage.cs ..\Core\Core\MessageProto\OuterMessage.cs
//xcopy /s /e /Y /f .\MessageProto\OuterOpcode.cs ..\Core\Core\MessageProto\OuterOpcode.cs


pause


















